#!/usr/bin/env python3
"""
generate_report.py — Convert nsg_analyzer JSON output into a structured Markdown report.

Usage:
    python generate_report.py --input reports/findings.json
    python generate_report.py --input reports/findings.json --output reports/AUDIT-20260310.md
    python generate_report.py --input reports/findings.json --client "Acme Corp"
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}

SEVERITY_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "HIGH":     "🟠 HIGH",
    "MEDIUM":   "🟡 MEDIUM",
    "LOW":      "🔵 LOW",
    "INFO":     "⚪ INFO",
}

# MITRE technique → tactic mapping for the coverage table
MITRE_TACTICS: dict[str, str] = {
    "T1021":     "Lateral Movement",
    "T1021.001": "Lateral Movement — Remote Desktop Protocol",
    "T1021.002": "Lateral Movement — SMB/Windows Admin Shares",
    "T1021.003": "Lateral Movement — DCOM",
    "T1021.004": "Lateral Movement — SSH",
    "T1021.006": "Lateral Movement — Windows Remote Management",
    "T1041":     "Exfiltration — Exfiltration Over C2 Channel",
    "T1071":     "Command & Control — Application Layer Protocol",
    "T1071.004": "Command & Control — DNS",
    "T1078":     "Persistence — Valid Accounts",
    "T1078.004": "Persistence — Cloud Accounts",
    "T1110":     "Credential Access — Brute Force",
    "T1190":     "Initial Access — Exploit Public-Facing Application",
    "T1530":     "Collection — Data from Cloud Storage",
    "T1552.001": "Credential Access — Credentials In Files",
    "T1552.007": "Credential Access — Container API",
    "T1609":     "Execution — Container Administration Command",
    "T1610":     "Execution — Deploy Container",
}


def risk_rating(score: int) -> str:
    if score >= 30:
        return "🔴 **CRITICAL RISK** — Immediate remediation required before production deployment"
    if score >= 15:
        return "🟠 **HIGH RISK** — Remediate within 72 hours"
    if score >= 5:
        return "🟡 **MEDIUM RISK** — Remediate within current sprint"
    if score > 0:
        return "🔵 **LOW RISK** — Address in next planned maintenance window"
    return "✅ **PASS** — No significant findings detected"


def generate_report(data: dict, client_name: str = "") -> str:
    meta = data["audit_metadata"]
    summary = data["summary"]
    findings = data["findings"]

    audit_date = meta["timestamp"][:10]
    rg = meta["resource_group"]
    score = summary["risk_score"]
    by_sev = summary["by_severity"]
    nsgs = meta["nsgs_audited"]

    client_line = f"**Client:** {client_name}  \n" if client_name else ""

    lines: list[str] = []

    # ── Cover ──────────────────────────────────────────────────────────────────────
    lines += [
        f"# Azure Security Baseline Audit Report",
        f"",
        f"{client_line}"
        f"**Resource Group:** `{rg}`  ",
        f"**Audit Date:** {audit_date}  ",
        f"**Subscription:** `{meta['subscription_id']}`  ",
        f"**Auditor Tool:** `{meta['tool']} v{meta['version']}`  ",
        f"**NSGs Audited:** {', '.join(f'`{n}`' for n in nsgs)}  ",
        f"",
        f"---",
        f"",
    ]

    # ── Executive Summary ──────────────────────────────────────────────────────────
    lines += [
        f"## Executive Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Overall Risk | {risk_rating(score)} |",
        f"| Risk Score | **{score} / 100** |",
        f"| Total Findings | {summary['total_findings']} |",
        f"| Critical | {by_sev.get('CRITICAL', 0)} |",
        f"| High | {by_sev.get('HIGH', 0)} |",
        f"| Medium | {by_sev.get('MEDIUM', 0)} |",
        f"| Low | {by_sev.get('LOW', 0)} |",
        f"",
    ]

    if not findings:
        lines += [
            "> **No findings detected.** The audited NSGs conform to the security baseline.",
            "",
            "---",
            "",
            f"*Generated by [azure-security-baseline](https://github.com/codewithbrandon/azure-security-baseline)*",
        ]
        return "\n".join(lines)

    # ── Key Observations ───────────────────────────────────────────────────────────
    critical_count = by_sev.get("CRITICAL", 0)
    high_count = by_sev.get("HIGH", 0)

    observations: list[str] = []
    if critical_count > 0:
        observations.append(
            f"- **{critical_count} Critical finding(s)** represent immediate breach risk and "
            "must be resolved before this environment handles sensitive data."
        )
    if high_count > 0:
        observations.append(
            f"- **{high_count} High finding(s)** expose management or database ports to the internet. "
            "These are the most commonly exploited misconfigurations found in breach investigations."
        )

    open_db_ports = [f for f in findings if f["finding_type"] == "OPEN_HIGH_RISK_PORT"
                     and any(p in f["description"] for p in ["SQL", "Mongo", "Redis", "Postgres", "MySQL"])]
    if open_db_ports:
        observations.append(
            "- **Database ports are exposed to the internet.** This is the most critical finding. "
            "Unauthenticated access to database services enables immediate data exfiltration."
        )

    if observations:
        lines += ["### Key Observations", ""]
        lines += observations
        lines += [""]

    # ── Findings Summary Table ─────────────────────────────────────────────────────
    lines += [
        "## Findings Summary",
        "",
        "| # | Severity | NSG | Rule | Type |",
        "|---|----------|-----|------|------|",
    ]
    for i, f in enumerate(findings, 1):
        badge = SEVERITY_BADGE.get(f["severity"], f["severity"])
        lines.append(
            f"| {i} | {badge} | `{f['nsg_name']}` | `{f['rule_name']}` | {f['finding_type']} |"
        )
    lines += ["", "---", ""]

    # ── Detailed Findings ──────────────────────────────────────────────────────────
    lines += ["## Detailed Findings", ""]

    for i, f in enumerate(findings, 1):
        badge = SEVERITY_BADGE.get(f["severity"], f["severity"])
        priority_row = f"| **Priority** | `{f['priority']}` |\n" if "priority" in f else ""

        lines += [
            f"### Finding {i} — {f['finding_type']}",
            f"",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| **Severity** | {badge} |",
            f"| **NSG** | `{f['nsg_name']}` |",
            f"| **Rule** | `{f['rule_name']}` |",
        ]
        if "priority" in f:
            lines.append(f"| **Priority** | `{f['priority']}` |")
        lines += [
            f"| **MITRE ATT&CK** | `{f.get('mitre_technique', 'N/A')}` |",
            f"",
            f"**Description:**",
            f"",
            f"> {f['description']}",
            f"",
            f"**Remediation:**",
            f"",
            f"> {f['remediation']}",
            f"",
            f"<details>",
            f"<summary>Resource ID</summary>",
            f"",
            f"```",
            f"{f.get('resource_id', 'N/A')}",
            f"```",
            f"",
            f"</details>",
            f"",
            "---",
            "",
        ]

    # ── MITRE ATT&CK Coverage ──────────────────────────────────────────────────────
    mitre_map: dict[str, set] = {}
    for f in findings:
        technique = f.get("mitre_technique", "")
        if technique and technique != "N/A":
            # Normalize: strip description after " — "
            key = technique.split(" — ")[0].strip()
            mitre_map.setdefault(key, set()).add(f["finding_type"])

    if mitre_map:
        lines += [
            "## MITRE ATT&CK Technique Mapping",
            "",
            "| Technique | Tactic | Finding Types Mapped |",
            "|-----------|--------|---------------------|",
        ]
        for technique in sorted(mitre_map):
            tactic = MITRE_TACTICS.get(technique, "—")
            types = ", ".join(sorted(mitre_map[technique]))
            lines.append(f"| [`{technique}`](https://attack.mitre.org/techniques/{technique.replace('.', '/')}) | {tactic} | {types} |")
        lines += [""]

    # ── Remediation Checklist ──────────────────────────────────────────────────────
    lines += [
        "## Remediation Checklist",
        "",
        "Work through findings in severity order. Do not mark complete until verified in Azure Portal or via re-audit.",
        "",
    ]
    for i, f in enumerate(findings, 1):
        badge = f["severity"]
        lines.append(f"- [ ] **[{badge}]** Finding {i}: `{f['nsg_name']} / {f['rule_name']}` — {f['finding_type']}")

    lines += [
        "",
        "---",
        "",
        "## Re-Audit Instructions",
        "",
        "After applying remediations, re-run the audit to confirm resolution:",
        "",
        "```bash",
        f"python scripts/nsg_analyzer.py \\",
        f"  --resource-group {rg} \\",
        f"  --output-json reports/findings-remediated.json",
        "",
        "python scripts/generate_report.py \\",
        f"  --input reports/findings-remediated.json \\",
        f"  --output reports/AUDIT-REMEDIATED-{audit_date}.md",
        "```",
        "",
        "---",
        "",
        f"*Report generated by [azure-security-baseline](https://github.com/codewithbrandon/azure-security-baseline)*  ",
        f"*{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
    ]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Markdown audit report from nsg_analyzer JSON output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--input", "-i", required=True,
                        help="Path to JSON findings file from nsg_analyzer.py")
    parser.add_argument("--output", "-o",
                        help="Output Markdown path (default: stdout)")
    parser.add_argument("--client", "-c", default="",
                        help="Client name to include in report header")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {args.input}")
        sys.exit(1)

    with open(input_path, encoding="utf-8") as fh:
        data = json.load(fh)

    report = generate_report(data, client_name=args.client)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"Report written to: {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
